// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtnngmRqAozvgZ8G-YWASO6YrXjydaYgY',
    appId: '1:815078820046:web:dc279eea2390c09cb7e89f',
    messagingSenderId: '815078820046',
    projectId: 'plantani-backend',
    authDomain: 'plantani-backend.firebaseapp.com',
    storageBucket: 'plantani-backend.appspot.com',
    measurementId: 'G-58M06TECHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcIY2qaRdxjAgORyn5Njnn01GPEiAQVzI',
    appId: '1:815078820046:android:2c379df000d782b4b7e89f',
    messagingSenderId: '815078820046',
    projectId: 'plantani-backend',
    storageBucket: 'plantani-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbHHFGuXB8mDvBe1tbVqiT2KRjbYmL3M8',
    appId: '1:815078820046:ios:af25c5dda9dae599b7e89f',
    messagingSenderId: '815078820046',
    projectId: 'plantani-backend',
    storageBucket: 'plantani-backend.appspot.com',
    iosClientId: '815078820046-j7dqmcd82cqnq1bie9fu6op0koqdtth0.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantaniFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbHHFGuXB8mDvBe1tbVqiT2KRjbYmL3M8',
    appId: '1:815078820046:ios:af25c5dda9dae599b7e89f',
    messagingSenderId: '815078820046',
    projectId: 'plantani-backend',
    storageBucket: 'plantani-backend.appspot.com',
    iosClientId: '815078820046-j7dqmcd82cqnq1bie9fu6op0koqdtth0.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantaniFlutter',
  );
}
